version: '3.7'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    entrypoint: ['./entrypoints/api.sh']
    container_name: api
    volumes:
      - ./app/:/opt/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - thenerdshop

  db:
    image: postgres:11-alpine
    container_name: db
    volumes:
      - thenerdshop_postgres:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=thenerdshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - thenerdshop

volumes:
  thenerdshop_postgres:

networks:
  thenerdshop:
