# Generated by Django 3.2.4 on 2021-06-09 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'E-mail'), ('intern', 'Interna')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.CharField(max_length=255, verbose_name='Notification Link')),
                ('body', models.TextField(blank=True, max_length=500, null=True, verbose_name='Texto da Notificação')),
                ('email_body', models.TextField(blank=True, null=True, verbose_name='Corpo do E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='crm/notification/icons', verbose_name='Ícone')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='crm/notification/banners', verbose_name='Baner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
