# Generated by Django 3.2.4 on 2021-06-09 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('code', models.CharField(max_length=100, verbose_name='Código')),
                ('reference', models.CharField(max_length=100, verbose_name='Referência')),
                ('transaction_type', models.IntegerField(verbose_name='Tipo')),
                ('transaction_status', models.IntegerField(verbose_name='Status')),
                ('last_event_date', models.DateTimeField(verbose_name='Data do Último Evento')),
                ('payment_method_type', models.IntegerField(verbose_name='Tipo do Método de Pagamento')),
                ('payment_method_code', models.IntegerField(verbose_name='Código do Método de Pagamento')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido')),
                ('extra_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Extra')),
                ('installment_count', models.IntegerField(verbose_name='Parcelas')),
                ('sender_name', models.CharField(max_length=100, verbose_name='Nome do Comprador')),
                ('sender_email', models.CharField(max_length=100, verbose_name='Email do Comprador')),
                ('sender_phone_code', models.CharField(max_length=2, verbose_name='DDD Telefone Comprador')),
                ('sender_phone_number', models.CharField(max_length=9, verbose_name='Telefone Comprador')),
                ('sender_cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Comprador')),
                ('payment_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link de Pagamento')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Produto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productsize', verbose_name='Tamanho')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.transaction', verbose_name='Transação')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
